INSERT INTO `countries` (`country_id`, `name`, `created_at`,`updated_at`) VALUES
('AD', 'Andorra', now(), now()),
('AE', 'United Arab Emirates', now(), now()),
('AF', 'Afghanistan', now(), now()),
('AG', 'Antigua and Barbuda', now(), now()),
('AI', 'Anguilla', now(), now()),
('AL', 'Albania', now(), now()),
('AM', 'Armenia', now(), now()),
('AN', 'Netherlands Antilles', now(), now()),
('AO', 'Angola', now(), now()),
('AQ', 'Antarctica', now(), now()),
('AR', 'Argentina', now(), now()),
('AS', 'American Samoa', now(), now()),
('AT', 'Austria', now(), now()),
('AU', 'Australia', now(), now()),
('AW', 'Aruba', now(), now()),
('AZ', 'Azerbaijan', now(), now()),
('BA', 'Bosnia and Herzegowina', now(), now()),
('BB', 'Barbados', now(), now()),
('BD', 'Bangladesh', now(), now()),
('BE', 'Belgium', now(), now()),
('BF', 'Burkina Faso', now(), now()),
('BG', 'Bulgaria', now(), now()),
('BH', 'Bahrain', now(), now()),
('BI', 'Burundi', now(), now()),
('BJ', 'Benin', now(), now()),
('BM', 'Bermuda', now(), now()),
('BN', 'Brunei Darussalam', now(), now()),
('BO', 'Bolivia', now(), now()),
('BR', 'Brazil', now(), now()),
('BS', 'Bahamas', now(), now()),
('BT', 'Bhutan', now(), now()),
('BV', 'Bouvet Island', now(), now()),
('BW', 'Botswana', now(), now()),
('BY', 'Belarus', now(), now()),
('BZ', 'Belize', now(), now()),
('CA', 'Canada', now(), now()),
('CC', 'Cocos (Keeling) Islands', now(), now()),
('CD', 'Congo, the Democratic Republic of the', now(), now()),
('CF', 'Central African Republic', now(), now()),
('CG', 'Congo', now(), now()),
('CH', 'Switzerland', now(), now()),
('CI', 'Cote d''Ivoire', now(), now()),
('CK', 'Cook Islands', now(), now()),
('CL', 'Chile', now(), now()),
('CM', 'Cameroon', now(), now()),
('CN', 'China', now(), now()),
('CO', 'Colombia', now(), now()),
('CR', 'Costa Rica', now(), now()),
('CU', 'Cuba', now(), now()),
('CV', 'Cape Verde', now(), now()),
('CX', 'Christmas Island', now(), now()),
('CY', 'Cyprus', now(), now()),
('CZ', 'Czech Republic', now(), now()),
('DE', 'Germany', now(), now()),
('DJ', 'Djibouti', now(), now()),
('DK', 'Denmark', now(), now()),
('DM', 'Dominica', now(), now()),
('DO', 'Dominican Republic', now(), now()),
('DZ', 'Algeria', now(), now()),
('EC', 'Ecuador', now(), now()),
('EE', 'Estonia', now(), now()),
('EG', 'Egypt', now(), now()),
('EH', 'Western Sahara', now(), now()),
('ER', 'Eritrea', now(), now()),
('ES', 'Spain', now(), now()),
('ET', 'Ethiopia', now(), now()),
('FI', 'Finland', now(), now()),
('FJ', 'Fiji', now(), now()),
('FK', 'Falkland Islands (Malvinas)', now(), now()),
('FM', 'Micronesia, Federated States of', now(), now()),
('FO', 'Faroe Islands', now(), now()),
('FR', 'France', now(), now()),
('FX', 'France, Metropolitan', now(), now()),
('GA', 'Gabon', now(), now()),
('GB', 'United Kingdom', now(), now()),
('GD', 'Grenada', now(), now()),
('GE', 'Georgia', now(), now()),
('GF', 'French Guiana', now(), now()),
('GH', 'Ghana', now(), now()),
('GI', 'Gibraltar', now(), now()),
('GL', 'Greenland', now(), now()),
('GM', 'Gambia', now(), now()),
('GN', 'Guinea', now(), now()),
('GP', 'Guadeloupe', now(), now()),
('GQ', 'Equatorial Guinea', now(), now()),
('GR', 'Greece', now(), now()),
('GS', 'South Georgia and the South Sandwich Islands', now(), now()),
('GT', 'Guatemala', now(), now()),
('GU', 'Guam', now(), now()),
('GW', 'Guinea-Bissau', now(), now()),
('GY', 'Guyana', now(), now()),
('HK', 'Hong Kong', now(), now()),
('HM', 'Heard and Mc Donald Islands', now(), now()),
('HN', 'Honduras', now(), now()),
('HR', 'Croatia (Hrvatska)', now(), now()),
('HT', 'Haiti', now(), now()),
('HU', 'Hungary', now(), now()),
('ID', 'Indonesia', now(), now()),
('IE', 'Ireland', now(), now()),
('IL', 'Israel', now(), now()),
('IN', 'India', now(), now()),
('IO', 'British Indian Ocean Territory', now(), now()),
('IQ', 'Iraq', now(), now()),
('IR', 'Iran (Islamic Republic of)', now(), now()),
('IS', 'Iceland', now(), now()),
('IT', 'Italy', now(), now()),
('JM', 'Jamaica', now(), now()),
('JO', 'Jordan', now(), now()),
('JP', 'Japan', now(), now()),
('KE', 'Kenya', now(), now()),
('KG', 'Kyrgyzstan', now(), now()),
('KH', 'Cambodia', now(), now()),
('KI', 'Kiribati', now(), now()),
('KM', 'Comoros', now(), now()),
('KN', 'Saint Kitts and Nevis', now(), now()),
('KP', 'Korea, Democratic People''s Republic of', now(), now()),
('KR', 'Korea, Republic of', now(), now()),
('KW', 'Kuwait', now(), now()),
('KY', 'Cayman Islands', now(), now()),
('KZ', 'Kazakhstan', now(), now()),
('LA', 'Lao People''s Democratic Republic', now(), now()),
('LB', 'Lebanon', now(), now()),
('LC', 'Saint LUCIA', now(), now()),
('LI', 'Liechtenstein', now(), now()),
('LK', 'Sri Lanka', now(), now()),
('LR', 'Liberia', now(), now()),
('LS', 'Lesotho', now(), now()),
('LT', 'Lithuania', now(), now()),
('LU', 'Luxembourg', now(), now()),
('LV', 'Latvia', now(), now()),
('LY', 'Libyan Arab Jamahiriya', now(), now()),
('MA', 'Morocco', now(), now()),
('MC', 'Monaco', now(), now()),
('MD', 'Moldova, Republic of', now(), now()),
('MG', 'Madagascar', now(), now()),
('MH', 'Marshall Islands', now(), now()),
('MK', 'Macedonia, The Former Yugoslav Republic of', now(), now()),
('ML', 'Mali', now(), now()),
('MM', 'Myanmar', now(), now()),
('MN', 'Mongolia', now(), now()),
('MO', 'Macau', now(), now()),
('MP', 'Northern Mariana Islands', now(), now()),
('MQ', 'Martinique', now(), now()),
('MR', 'Mauritania', now(), now()),
('MS', 'Montserrat', now(), now()),
('MT', 'Malta', now(), now()),
('MU', 'Mauritius', now(), now()),
('MV', 'Maldives', now(), now()),
('MW', 'Malawi', now(), now()),
('MX', 'Mexico', now(), now()),
('MY', 'Malaysia', now(), now()),
('MZ', 'Mozambique', now(), now()),
('NA', 'Namibia', now(), now()),
('NC', 'New Caledonia', now(), now()),
('NE', 'Niger', now(), now()),
('NF', 'Norfolk Island', now(), now()),
('NG', 'Nigeria', now(), now()),
('NI', 'Nicaragua', now(), now()),
('NL', 'Netherlands', now(), now()),
('NO', 'Norway', now(), now()),
('NP', 'Nepal', now(), now()),
('NR', 'Nauru', now(), now()),
('NU', 'Niue', now(), now()),
('NZ', 'New Zealand', now(), now()),
('OM', 'Oman', now(), now()),
('PA', 'Panama', now(), now()),
('PE', 'Peru', now(), now()),
('PF', 'French Polynesia', now(), now()),
('PG', 'Papua New Guinea', now(), now()),
('PH', 'Philippines', now(), now()),
('PK', 'Pakistan', now(), now()),
('PL', 'Poland', now(), now()),
('PM', 'St. Pierre and Miquelon', now(), now()),
('PN', 'Pitcairn', now(), now()),
('PR', 'Puerto Rico', now(), now()),
('PT', 'Portugal', now(), now()),
('PW', 'Palau', now(), now()),
('PY', 'Paraguay', now(), now()),
('QA', 'Qatar', now(), now()),
('RE', 'Reunion', now(), now()),
('RO', 'Romania', now(), now()),
('RU', 'Russian Federation', now(), now()),
('RW', 'Rwanda', now(), now()),
('SA', 'Saudi Arabia', now(), now()),
('SB', 'Solomon Islands', now(), now()),
('SC', 'Seychelles', now(), now()),
('SD', 'Sudan', now(), now()),
('SE', 'Sweden', now(), now()),
('SG', 'Singapore', now(), now()),
('SH', 'St. Helena', now(), now()),
('SI', 'Slovenia', now(), now()),
('SJ', 'Svalbard and Jan Mayen Islands', now(), now()),
('SK', 'Slovakia (Slovak Republic)', now(), now()),
('SL', 'Sierra Leone', now(), now()),
('SM', 'San Marino', now(), now()),
('SN', 'Senegal', now(), now()),
('SO', 'Somalia', now(), now()),
('SR', 'Suriname', now(), now()),
('ST', 'Sao Tome and Principe', now(), now()),
('SV', 'El Salvador', now(), now()),
('SY', 'Syrian Arab Republic', now(), now()),
('SZ', 'Swaziland', now(), now()),
('TC', 'Turks and Caicos Islands', now(), now()),
('TD', 'Chad', now(), now()),
('TF', 'French Southern Territories', now(), now()),
('TG', 'Togo', now(), now()),
('TH', 'Thailand', now(), now()),
('TJ', 'Tajikistan', now(), now()),
('TK', 'Tokelau', now(), now()),
('TM', 'Turkmenistan', now(), now()),
('TN', 'Tunisia', now(), now()),
('TO', 'Tonga', now(), now()),
('TP', 'East Timor', now(), now()),
('TR', 'Turkey', now(), now()),
('TT', 'Trinidad and Tobago', now(), now()),
('TV', 'Tuvalu', now(), now()),
('TW', 'Taiwan, Province of China', now(), now()),
('TZ', 'Tanzania, United Republic of', now(), now()),
('UA', 'Ukraine', now(), now()),
('UG', 'Uganda', now(), now()),
('UM', 'United States Minor Outlying Islands', now(), now()),
('US', 'United States', now(), now()),
('UY', 'Uruguay', now(), now()),
('UZ', 'Uzbekistan', now(), now()),
('VA', 'Holy See (Vatican City State)', now(), now()),
('VC', 'Saint Vincent and the Grenadines', now(), now()),
('VE', 'Venezuela', now(), now()),
('VG', 'Virgin Islands (British)', now(), now()),
('VI', 'Virgin Islands (U.S.)', now(), now()),
('VN', 'Viet Nam', now(), now()),
('VU', 'Vanuatu', now(), now()),
('WF', 'Wallis and Futuna Islands', now(), now()),
('WS', 'Samoa', now(), now()),
('YE', 'Yemen', now(), now()),
('YT', 'Mayotte', now(), now()),
('YU', 'Yugoslavia', now(), now()),
('ZA', 'South Africa', now(), now()),
('ZM', 'Zambia', now(), now()),
('ZW', 'Zimbabwe', now(), now());
