INSERT IGNORE INTO `signs` (`id`, `text`) VALUES
("Abdominal Bruits" , "Abdominal Bruits"),
("Abdominal Distension" , "Abdominal Distension"),
("Abdominal Guarding" , "Abdominal Guarding"),
("Abdominal Masses" , "Abdominal Masses"),
("Abdominal Pulsation" , "Abdominal Pulsation"),
("Abdominal Rigidity" , "Abdominal Rigidity"),
("Abdominal Scars" , "Abdominal Scars"),
("Abnormal Carotid Pulse Character" , "Abnormal Carotid Pulse Character"),
("Abnormal Dentition" , "Abnormal Dentition"),
("Abnormal Gait" , "Abnormal Gait"),
("Absent Corneal Reflex" , "Absent Corneal Reflex"),
("Absent Lower Limb Pulses" , "Absent Lower Limb Pulses"),
("Absent Pharyngeal Reflex" , "Absent Pharyngeal Reflex"),
("Absent Pupillary Light Reflexes" , "Absent Pupillary Light Reflexes"),
("Acetone Breath" , "Acetone Breath"),
("Adie’s Tonic Pupil" , "Adie’s Tonic Pupil"),
("Affect" , "Affect"),
("Alcoholic Foetor" , "Alcoholic Foetor"),
("Angular Cheilitis" , "Angular Cheilitis"),
("Anisocoria (Unequal Pupils)" , "Anisocoria (Unequal Pupils)"),
("Anomia" , "Anomia"),
("Anosmia" , "Anosmia"),
("Antalgic Gait" , "Antalgic Gait"),
("Anterior Draw Test" , "Anterior Draw Test"),
("Anterograde Amnesia" , "Anterograde Amnesia"),
("Apley Scratch Test" , "Apley Scratch Test"),
("Appearance" , "Appearance"),
("Apprehension Test" , "Apprehension Test"),
("Appropriateness of Affect" , "Appropriateness of Affect"),
("Apraxia" , "Apraxia"),
("Apraxic Gait" , "Apraxic Gait"),
("Argyll Robertson Pupil" , "Argyll Robertson Pupil"),
("Arm Elevation Test" , "Arm Elevation Test"),
("Arterial Skin Changes" , "Arterial Skin Changes"),
("Arteriovenous Fistulas" , "Arteriovenous Fistulas"),
("Asterixis" , "Asterixis"),
("Asymmetric Soft Palate Rise" , "Asymmetric Soft Palate Rise"),
("Ataxic Gait" , "Ataxic Gait"),
("Atrophic Glossitis" , "Atrophic Glossitis"),
("Auditory Acuity" , "Auditory Acuity"),
("Auditory Hallucinations" , "Auditory Hallucinations"),
("Augmentation Test" , "Augmentation Test"),
("Babinski Sign" , "Babinski Sign"),
("Baker’s Cyst" , "Baker’s Cyst"),
("Barrel Chest" , "Barrel Chest"),
("Bier Spots" , "Bier Spots"),
("Bitemporal Hemianopia" , "Bitemporal Hemianopia"),
("Bladder Distension" , "Bladder Distension"),
("Bony Tenderness" , "Bony Tenderness"),
("Bouchard’s Nodes" , "Bouchard’s Nodes"),
("Boutonniere Deformity" , "Boutonniere Deformity"),
("Bowel Sounds" , "Bowel Sounds"),
("Bradycardia" , "Bradycardia"),
("Bradykinesia / Hypokinesia" , "Bradykinesia / Hypokinesia"),
("Bradypnoea" , "Bradypnoea"),
("Bronchial Sounds" , "Bronchial Sounds"),
("Bulbar Fatigability" , "Bulbar Fatigability"),
("Callosities of the Ankle and Foot" , "Callosities of the Ankle and Foot"),
("Capillary Refill Time" , "Capillary Refill Time"),
("Caput Medusae" , "Caput Medusae"),
("Carotid Bruit" , "Carotid Bruit"),
("Category Fluency" , "Category Fluency"),
("Central Cyanosis" , "Central Cyanosis"),
("Central Visual Fields" , "Central Visual Fields"),
("Centre of Gravity" , "Centre of Gravity"),
("Cervical Hyperlordosis" , "Cervical Hyperlordosis"),
("Charcot Foot" , "Charcot Foot"),
("Chest Expansion" , "Chest Expansion"),
("Chest Wall Tenderness" , "Chest Wall Tenderness"),
("Cheyne-Stokes Respiration" , "Cheyne-Stokes Respiration"),
("Chorea" , "Chorea"),
("Circumlocution" , "Circumlocution"),
("Claw Hand" , "Claw Hand"),
("Claw Toe" , "Claw Toe"),
("Clonus" , "Clonus"),
("Cog Wheel Rigidity" , "Cog Wheel Rigidity"),
("Collapsing Pulse" , "Collapsing Pulse"),
("Colour Vision" , "Colour Vision"),
("Conceptualisation" , "Conceptualisation"),
("Confusion" , "Confusion"),
("Conjunctival Pallor" , "Conjunctival Pallor"),
("Continuous Murmur" , "Continuous Murmur"),
("Cool Extremities" , "Cool Extremities"),
("Cough" , "Cough"),
("Cover Test" , "Cover Test"),
("Cozen’s Test" , "Cozen’s Test"),
("Crackles / Crepitations" , "Crackles / Crepitations"),
("Cullen’s Sign" , "Cullen’s Sign"),
("Dactylitis" , "Dactylitis"),
("Decreased Tactile Fremitus" , "Decreased Tactile Fremitus"),
("Dehydration" , "Dehydration"),
("Dental Caries" , "Dental Caries"),
("Dental Erosions" , "Dental Erosions"),
("Dental Trauma" , "Dental Trauma"),
("Depressive Thought Content" , "Depressive Thought Content"),
("Diabetic Retinopathy" , "Diabetic Retinopathy"),
("Diastolic Murmur" , "Diastolic Murmur"),
("Digital Clubbing" , "Digital Clubbing"),
("Diplopia" , "Diplopia"),
("Disordered Reading" , "Disordered Reading"),
("Disordered Writing" , "Disordered Writing"),
("Displaced Apex Beat" , "Displaced Apex Beat"),
("Dissociative Symptoms" , "Dissociative Symptoms"),
("Distal Weakness" , "Distal Weakness"),
("Distractibility" , "Distractibility"),
("Double Impulse Apex Beat" , "Double Impulse Apex Beat"),
("Dull Percussion Note" , "Dull Percussion Note"),
("Dupuytren’s Contracture" , "Dupuytren’s Contracture"),
("Dysdiadochokinesis" , "Dysdiadochokinesis"),
("Dysmegalopsia" , "Dysmegalopsia"),
("Dystonia" , "Dystonia"),
("Echophenomena" , "Echophenomena"),
("Elbow Bruising" , "Elbow Bruising"),
("Elbow Carrying Angle" , "Elbow Carrying Angle"),
("Elbow Deformity" , "Elbow Deformity"),
("Empty Can Test" , "Empty Can Test"),
("Exaggerated Pharyngeal Reflex" , "Exaggerated Pharyngeal Reflex"),
("Facial Weakness" , "Facial Weakness"),
("Fasciculations" , "Fasciculations"),
("Femoral Nerve Stretch Test" , "Femoral Nerve Stretch Test"),
("Festinating Gait" , "Festinating Gait"),
("Finger-Nose Test" , "Finger-Nose Test"),
("First Heart Sound" , "First Heart Sound"),
("Fissure in Ano" , "Fissure in Ano"),
("Flank Tenderness" , "Flank Tenderness"),
("Flexor Tendon Crepitus" , "Flexor Tendon Crepitus"),
("Fluid Overload" , "Fluid Overload"),
("Fluid Wave" , "Fluid Wave"),
("Focal Abdominal Tenderness" , "Focal Abdominal Tenderness"),
("Foetor Hepaticus" , "Foetor Hepaticus"),
("Foot Drop" , "Foot Drop"),
("Foot Position" , "Foot Position"),
("Formal Thought Disorders" , "Formal Thought Disorders"),
("Fourth Heart Sound" , "Fourth Heart Sound"),
("Generalised Abdominal Tenderness" , "Generalised Abdominal Tenderness"),
("Genu Recurvatum (Back-Knee)" , "Genu Recurvatum (Back-Knee)"),
("Genu Valgum (Knock-Knee)" , "Genu Valgum (Knock-Knee)"),
("Genu Varum (Bow Leg)" , "Genu Varum (Bow Leg)"),
("Gingival Bleeding" , "Gingival Bleeding"),
("Gingival Hypertrophy" , "Gingival Hypertrophy"),
("Gingival Inflammation" , "Gingival Inflammation"),
("Gottron’s Papules" , "Gottron’s Papules"),
("Grey-Turner’s Sign" , "Grey-Turner’s Sign"),
("Gynaecomastia" , "Gynaecomastia"),
("Haemorrhoids" , "Haemorrhoids"),
("Halitosis" , "Halitosis"),
("Hallux Valgus" , "Hallux Valgus"),
("Hand of Benediction" , "Hand of Benediction"),
("Harsh Speech" , "Harsh Speech"),
("Heberden’s Nodes" , "Heberden’s Nodes"),
("Heel Walking" , "Heel Walking"),
("Heel-to-Shin Test" , "Heel-to-Shin Test"),
("Hepatomegaly" , "Hepatomegaly"),
("Herniae" , "Herniae"),
("High-Arched Palate" , "High-Arched Palate"),
("Hoarseness" , "Hoarseness"),
("Homonymous Hemianopia" , "Homonymous Hemianopia"),
("Homonymous Quadrantanopia" , "Homonymous Quadrantanopia"),
("Hyperactivity" , "Hyperactivity"),
("Hyperaesthesia" , "Hyperaesthesia"),
("Hypernasal Speech" , "Hypernasal Speech"),
("Hyperpigmentation" , "Hyperpigmentation"),
("Hyperreflexia" , "Hyperreflexia"),
("Hyperresonant Percussion Note" , "Hyperresonant Percussion Note"),
("Hypertension" , "Hypertension"),
("Hypertensive Retinopathy" , "Hypertensive Retinopathy"),
("Hypoaesthesia" , "Hypoaesthesia"),
("Hypophonia" , "Hypophonia"),
("Hyporeflexia" , "Hyporeflexia"),
("Hypotension" , "Hypotension"),
("Illusions" , "Illusions"),
("Impaired Accommodation" , "Impaired Accommodation"),
("Impaired Digit Span" , "Impaired Digit Span"),
("Impaired Rapid Foot Tapping" , "Impaired Rapid Foot Tapping"),
("Increased Anal Sphincter Tone" , "Increased Anal Sphincter Tone"),
("Increased Body Mass Index" , "Increased Body Mass Index"),
("Increased Body Temperature" , "Increased Body Temperature"),
("Increased Glabellar Reflex" , "Increased Glabellar Reflex"),
("Increased Tactile Fremitus" , "Increased Tactile Fremitus"),
("Increased Vocal Resonance" , "Increased Vocal Resonance"),
("Increased Waist-Hip Ratio" , "Increased Waist-Hip Ratio"),
("Ingrown Toenails" , "Ingrown Toenails"),
("Inhibitory Control" , "Inhibitory Control"),
("Injection Sites" , "Injection Sites"),
("Insight" , "Insight"),
("Intensity of Affect" , "Intensity of Affect"),
("Intention Tremor" , "Intention Tremor"),
("Internuclear Ophthalmoplegia" , "Internuclear Ophthalmoplegia"),
("Irregular Pulse" , "Irregular Pulse"),
("Irritability" , "Irritability"),
("Janeway Lesions" , "Janeway Lesions"),
("Jaundice" , "Jaundice"),
("Jaw Jerk" , "Jaw Jerk"),
("Jerk Nystagmus" , "Jerk Nystagmus"),
("Kayser-Fleischer Rings" , "Kayser-Fleischer Rings"),
("Koilonychia" , "Koilonychia"),
("Kolbel's Bow Test" , "Kolbel's Bow Test"),
("Kussmaul Respiration" , "Kussmaul Respiration"),
("Lability of Mood" , "Lability of Mood"),
("Lead Pipe Rigidity" , "Lead Pipe Rigidity"),
("Leg Length Discrepancy" , "Leg Length Discrepancy"),
("Leg Tenderness" , "Leg Tenderness"),
("Lesser Toe Deformities" , "Lesser Toe Deformities"),
("Leukonychia" , "Leukonychia"),
("Level of Happiness" , "Level of Happiness"),
("Lhermitte’s Sign" , "Lhermitte’s Sign"),
("Lift Off Test" , "Lift Off Test"),
("Light Touch Sensation" , "Light Touch Sensation"),
("Limitation of Extraocular Movement" , "Limitation of Extraocular Movement"),
("Limited Active Movement" , "Limited Active Movement"),
("Lip Pigmentation" , "Lip Pigmentation"),
("Lip Ulceration" , "Lip Ulceration"),
("Liver Nodularity" , "Liver Nodularity"),
("Log Roll Test" , "Log Roll Test"),
("Loss of Cervical Lordosis" , "Loss of Cervical Lordosis"),
("Loss of Chest Hair Distribution" , "Loss of Chest Hair Distribution"),
("Loss of Lumbar Lordosis" , "Loss of Lumbar Lordosis"),
("Loss of Proprioception" , "Loss of Proprioception"),
("Loud P2" , "Loud P2"),
("Lower Limb Erythema" , "Lower Limb Erythema"),
("Lower Motor Neuron Weakness" , "Lower Motor Neuron Weakness"),
("Lymphadenopathy" , "Lymphadenopathy"),
("Mastoid Tenderness" , "Mastoid Tenderness"),
("McBurney’s Point Tenderness" , "McBurney’s Point Tenderness"),
("McMurray’s Test for the Lateral Meniscus" , "McMurray’s Test for the Lateral Meniscus"),
("McMurray’s Test for the Medial Meniscus" , "McMurray’s Test for the Medial Meniscus"),
("Micrographia" , "Micrographia"),
("Miosis" , "Miosis"),
("Mitral Facies" , "Mitral Facies"),
("Mixed UMN and LMN Weakness" , "Mixed UMN and LMN Weakness"),
("Mouth Ulcers" , "Mouth Ulcers"),
("Murphy’s Sign" , "Murphy’s Sign"),
("Muscle Wasting" , "Muscle Wasting"),
("Mydriasis" , "Mydriasis"),
("Myoclonus" , "Myoclonus"),
("Myopathic Facies" , "Myopathic Facies"),
("Nail Bed Cyanosis" , "Nail Bed Cyanosis"),
("Nail Pitting" , "Nail Pitting"),
("Narrow Pulse Pressure" , "Narrow Pulse Pressure"),
("Nasal Discharge" , "Nasal Discharge"),
("Nasal Septal Deviation" , "Nasal Septal Deviation"),
("Nasal Septal Perforation" , "Nasal Septal Perforation"),
("Nasal Sinus Tenderness" , "Nasal Sinus Tenderness"),
("Neer Sign" , "Neer Sign"),
("Neologisms" , "Neologisms"),
("Neuropathic Ulcers" , "Neuropathic Ulcers"),
("Non-Pitting Oedema" , "Non-Pitting Oedema"),
("Obsessions" , "Obsessions"),
("Onycholysis" , "Onycholysis"),
("Oral Candidiasis" , "Oral Candidiasis"),
("Osler's Nodes" , "Osler's Nodes"),
("Pain on Eye Movement" , "Pain on Eye Movement"),
("Pain Sensation" , "Pain Sensation"),
("Pallor of the Nail Bed" , "Pallor of the Nail Bed"),
("Palmar Crease Pallor" , "Palmar Crease Pallor"),
("Palmar Erythema" , "Palmar Erythema"),
("Palpable Kidney" , "Palpable Kidney"),
("Palpable Thrill" , "Palpable Thrill"),
("Paradoxical Respiration" , "Paradoxical Respiration"),
("Paraphasias" , "Paraphasias"),
("Parasternal Heave" , "Parasternal Heave"),
("Paronychia" , "Paronychia"),
("Patellar Apprehension Test" , "Patellar Apprehension Test"),
("Patellar Bulge Test" , "Patellar Bulge Test"),
("Patellar Crepitus" , "Patellar Crepitus"),
("Patellar Tap" , "Patellar Tap"),
("Pectus Carinatum (Pigeon Chest)" , "Pectus Carinatum (Pigeon Chest)"),
("Pectus Excavatum (Funnel Chest)" , "Pectus Excavatum (Funnel Chest)"),
("Peek Sign" , "Peek Sign"),
("Pendular Nystagmus" , "Pendular Nystagmus"),
("Percussion Myotonia" , "Percussion Myotonia"),
("Percussion Tenderness" , "Percussion Tenderness"),
("Perianal Blood" , "Perianal Blood"),
("Perianal Mass" , "Perianal Mass"),
("Perianal Rash" , "Perianal Rash"),
("Perianal Sinus / Fistula" , "Perianal Sinus / Fistula"),
("Periauricular Vesicles" , "Periauricular Vesicles"),
("Pericardial Rub" , "Pericardial Rub"),
("Perioral Telangiectasias" , "Perioral Telangiectasias"),
("Peripheral Nerve Enlargement" , "Peripheral Nerve Enlargement"),
("Peripheral Visual Fields" , "Peripheral Visual Fields"),
("Pes Cavus" , "Pes Cavus"),
("Pes Planus" , "Pes Planus"),
("Phalen’s Test" , "Phalen’s Test"),
("Pharyngeal Erythema" , "Pharyngeal Erythema"),
("Pharyngeal Exudate" , "Pharyngeal Exudate"),
("Pitting Oedema" , "Pitting Oedema"),
("Pleural Rub" , "Pleural Rub"),
("Poor Posture" , "Poor Posture"),
("Posterior Draw Test" , "Posterior Draw Test"),
("Postural Hypotension" , "Postural Hypotension"),
("Postural Tachycardia" , "Postural Tachycardia"),
("Postural Tremor" , "Postural Tremor"),
("Pressure-Loaded Apex Beat" , "Pressure-Loaded Apex Beat"),
("Pronator Drift" , "Pronator Drift"),
("Prostate Enlargement" , "Prostate Enlargement"),
("Prostate Nodularity" , "Prostate Nodularity"),
("Prostate Tenderness" , "Prostate Tenderness"),
("Proximal Muscle Fatigability" , "Proximal Muscle Fatigability"),
("Proximal Myopathy" , "Proximal Myopathy"),
("Psoriatic Plaques" , "Psoriatic Plaques"),
("Psychogenic Tremor" , "Psychogenic Tremor"),
("Psychomotor Agitation" , "Psychomotor Agitation"),
("Psychomotor Retardation" , "Psychomotor Retardation"),
("Psychotic Thought Content" , "Psychotic Thought Content"),
("Ptosis" , "Ptosis"),
("Pull Test" , "Pull Test"),
("Pulsatile Abdominal Mass" , "Pulsatile Abdominal Mass"),
("Pulsus Paradoxus" , "Pulsus Paradoxus"),
("Purpura" , "Purpura"),
("Radio-Femoral Delay" , "Radio-Femoral Delay"),
("Radio-Radial Delay" , "Radio-Radial Delay"),
("Raised Jugular Venous Pressure" , "Raised Jugular Venous Pressure"),
("Range of Affect" , "Range of Affect"),
("Raynaud’s Phenomenon" , "Raynaud’s Phenomenon"),
("Reactivity of Mood" , "Reactivity of Mood"),
("Rebound Tenderness" , "Rebound Tenderness"),
("Rectal Blood" , "Rectal Blood"),
("Rectal Mass" , "Rectal Mass"),
("Rectal Wall Tenderness" , "Rectal Wall Tenderness"),
("Reduced Anal Sphincter Tone" , "Reduced Anal Sphincter Tone"),
("Reduced Body Mass Index" , "Reduced Body Mass Index"),
("Reduced Body Temperature" , "Reduced Body Temperature"),
("Reduced Breath Sounds" , "Reduced Breath Sounds"),
("Reduced Facial Sensation" , "Reduced Facial Sensation"),
("Reduced Glabellar Reflex" , "Reduced Glabellar Reflex"),
("Reduced Glasgow Coma Scale" , "Reduced Glasgow Coma Scale"),
("Reduced Oxygen Saturation" , "Reduced Oxygen Saturation"),
("Reduced Range of Motion" , "Reduced Range of Motion"),
("Reduced Visual Acuity" , "Reduced Visual Acuity"),
("Reduced Vocal Resonance" , "Reduced Vocal Resonance"),
("Relative Afferent Pupillary Defect" , "Relative Afferent Pupillary Defect"),
("Relocation Test" , "Relocation Test"),
("Repeated Movements" , "Repeated Movements"),
("Respiratory Distress" , "Respiratory Distress"),
("Resting Tremor" , "Resting Tremor"),
("Retrograde Amnesia" , "Retrograde Amnesia"),
("Richmond Agitation-Sedation Scale" , "Richmond Agitation-Sedation Scale"),
("Rinne’s Test" , "Rinne’s Test"),
("Romberg Test" , "Romberg Test"),
("Roth Spots" , "Roth Spots"),
("Rovsing’s Sign" , "Rovsing’s Sign"),
("Sacral Oedema" , "Sacral Oedema"),
("Salivary Gland Enlargement" , "Salivary Gland Enlargement"),
("Scapular Winging" , "Scapular Winging"),
("Scleral Icterus" , "Scleral Icterus"),
("Sclerodactyly" , "Sclerodactyly"),
("Scoliosis" , "Scoliosis"),
("Scratch Marks" , "Scratch Marks"),
("Shifting Dullness" , "Shifting Dullness"),
("Short Leg Gait" , "Short Leg Gait"),
("Simmonds-Thompson Text" , "Simmonds-Thompson Text"),
("Simpson’s Test" , "Simpson’s Test"),
("Skin Pallor" , "Skin Pallor"),
("Snapping Knee Joint" , "Snapping Knee Joint"),
("Soft A2" , "Soft A2"),
("Spastic Gait" , "Spastic Gait"),
("Spasticity" , "Spasticity"),
("Spider Naevi" , "Spider Naevi"),
("Splenomegaly" , "Splenomegaly"),
("Splinter Haemorrhages" , "Splinter Haemorrhages"),
("Sputum" , "Sputum"),
("Squat Test" , "Squat Test"),
("Stability of Affect" , "Stability of Affect"),
("Strabismus" , "Strabismus"),
("Straight Leg Raise" , "Straight Leg Raise"),
("Striae (Stretch Marks)" , "Striae (Stretch Marks)"),
("Stridor" , "Stridor"),
("Subconjunctival Haemorrhage" , "Subconjunctival Haemorrhage"),
("Succussion Splash" , "Succussion Splash"),
("Swan Neck Deformity" , "Swan Neck Deformity"),
("Systolic Murmur" , "Systolic Murmur"),
("Tachycardia" , "Tachycardia"),
("Tachypnoea" , "Tachypnoea"),
("Tandem Walking" , "Tandem Walking"),
("Tar Staining" , "Tar Staining"),
("Telegraphic Speech" , "Telegraphic Speech"),
("Tenckhoff Catheters" , "Tenckhoff Catheters"),
("Testing for Golfer's Elbow" , "Testing for Golfer's Elbow"),
("The Angle of the Heel" , "The Angle of the Heel"),
("The Patient's Attitude" , "The Patient's Attitude"),
("Third Heart Sound" , "Third Heart Sound"),
("Thomas Test" , "Thomas Test"),
("Thoracic Hyperkyphosis" , "Thoracic Hyperkyphosis"),
("Thoracic Scars" , "Thoracic Scars"),
("Tics" , "Tics"),
("Tinel's Sign of the Elbow" , "Tinel's Sign of the Elbow"),
("Tinel’s Sign at the Wrist" , "Tinel’s Sign at the Wrist"),
("Toe Walking" , "Toe Walking"),
("Tongue Deviation" , "Tongue Deviation"),
("Tongue Fasciculations" , "Tongue Fasciculations"),
("Tongue Ulcers" , "Tongue Ulcers"),
("Tongue Wasting" , "Tongue Wasting"),
("Tonsillar Swelling" , "Tonsillar Swelling"),
("Torticollis" , "Torticollis"),
("Tracheal Deviation" , "Tracheal Deviation"),
("Tracheal Tug" , "Tracheal Tug"),
("Trapezius and Sternocleidomastoid Weakness" , "Trapezius and Sternocleidomastoid Weakness"),
("Trendelenburg Gait" , "Trendelenburg Gait"),
("Trendelenburg Test" , "Trendelenburg Test"),
("Ulnar Deviation of the Wrist" , "Ulnar Deviation of the Wrist"),
("Ulnar Nerve Subluxation" , "Ulnar Nerve Subluxation"),
("Uncover Test" , "Uncover Test"),
("Unilateral Anopia" , "Unilateral Anopia"),
("Upper Motor Neuron Weakness" , "Upper Motor Neuron Weakness"),
("Uraemic Foetor" , "Uraemic Foetor"),
("Uvular Displacement" , "Uvular Displacement"),
("Valgus Stability Test (Elbow)" , "Valgus Stability Test (Elbow)"),
("Valgus Stress Test (Knee)" , "Valgus Stress Test (Knee)"),
("Varicose Veins" , "Varicose Veins"),
("Varus Stability Test (Elbow)" , "Varus Stability Test (Elbow)"),
("Varus Stress Test (Knee)" , "Varus Stress Test (Knee)"),
("Venous Skin Changes" , "Venous Skin Changes"),
("Verbal Comprehension" , "Verbal Comprehension"),
("Vibration Sense" , "Vibration Sense"),
("Visible Peristalsis" , "Visible Peristalsis"),
("Visual Hallucinations" , "Visual Hallucinations"),
("Visual Neglect" , "Visual Neglect"),
("Volume-Loaded Apex Beat" , "Volume-Loaded Apex Beat"),
("Warm Extremities" , "Warm Extremities"),
("Warm-Up Phenomenon" , "Warm-Up Phenomenon"),
("Wasting of the Hand Muscles" , "Wasting of the Hand Muscles"),
("Weakness of the Muscles of Mastication" , "Weakness of the Muscles of Mastication"),
("Weber’s Test" , "Weber’s Test"),
("Wheeze" , "Wheeze"),
("Wide Splitting of S2" , "Wide Splitting of S2"),
("Widened Pulse Pressure" , "Widened Pulse Pressure"),
("Word Repetition" , "Word Repetition"),
("Wrist Drop" , "Wrist Drop"),
("Wrist Swelling" , "Wrist Swelling"),
("Written Comprehension" , "Written Comprehension"),
("Xanthelasma" , "Xanthelasma"),
("Xanthomata" , "Xanthomata"),
("Z-Thumb Deformity" , "Z-Thumb Deformity"),
("Aaron sign" , "Aaron sign"),
("Abadie's sign" , "Abadie's sign"),
("Abadie's symptom" , "Abadie's symptom"),
("Abderhalden reaction" , "Abderhalden reaction"),
("Abelin reaction" , "Abelin reaction"),
("Addis count" , "Addis count"),
("Adie pupil" , "Adie pupil"),
("Adson's sign" , "Adson's sign"),
("Alexander's law" , "Alexander's law"),
("Allen's test" , "Allen's test"),
("Apgar score" , "Apgar score"),
("Apley grind test" , "Apley grind test"),
("Argyll Robertson pupils" , "Argyll Robertson pupils"),
("Arneth count" , "Arneth count"),
("Asboe-Hansen sign" , "Asboe-Hansen sign"),
("Aschheim–Zondek test" , "Aschheim–Zondek test"),
("Aschoff body" , "Aschoff body"),
("Ashby technique" , "Ashby technique"),
("Auberger's blood group" , "Auberger's blood group"),
("Auenbrugger's sign" , "Auenbrugger's sign"),
("Auer rods" , "Auer rods"),
("Auspitz's sign" , "Auspitz's sign"),
("Austin Flint murmur" , "Austin Flint murmur"),
("Babinski sign" , "Babinski sign"),
("Bainbridge reflex" , "Bainbridge reflex"),
("Balbiani rings" , "Balbiani rings"),
("Ballance's sign" , "Ballance's sign"),
("Bancroft's sign" , "Bancroft's sign"),
("Bárány test" , "Bárány test"),
("Barlow's maneuver" , "Barlow's maneuver"),
("Bart hemoglobin" , "Bart hemoglobin"),
("Bastian–Bruns sign" , "Bastian–Bruns sign"),
("Battle's sign" , "Battle's sign"),
("Beau's lines" , "Beau's lines"),
("Beck's triad" , "Beck's triad"),
("Becker's sign" , "Becker's sign"),
("Beevor's sign" , "Beevor's sign"),
("Bekhterev–Jacobsohn reflex" , "Bekhterev–Jacobsohn reflex"),
("Bekhterev–Mendel reflex" , "Bekhterev–Mendel reflex"),
("Bence Jones protein" , "Bence Jones protein"),
("Benedict solution" , "Benedict solution"),
("Berger wave (rhythm)" , "Berger wave (rhythm)"),
("Bezold–Jarisch reflex" , "Bezold–Jarisch reflex"),
("Bielschowsky's head tilt test" , "Bielschowsky's head tilt test"),
("Bing's sign" , "Bing's sign"),
("Biot's respiration" , "Biot's respiration"),
("Bitot's spots" , "Bitot's spots"),
("Bjerrum scotoma" , "Bjerrum scotoma"),
("Blumberg sign" , "Blumberg sign"),
("Boas' point" , "Boas' point"),
("Boas' sign" , "Boas' sign"),
("Bodansky unit" , "Bodansky unit"),
("Boston's sign" , "Boston's sign"),
("Bouchard's nodes" , "Bouchard's nodes"),
("Bracht–Wachter bodies" , "Bracht–Wachter bodies"),
("Branham's sign" , "Branham's sign"),
("Braxton Hicks contraction" , "Braxton Hicks contraction"),
("Brewer infarcts" , "Brewer infarcts"),
("Brissaud's reflex" , "Brissaud's reflex"),
("Broadbent inverted sign" , "Broadbent inverted sign"),
("Broadbent sign" , "Broadbent sign"),
("Broca aphasia" , "Broca aphasia"),
("Brodie–Trendelenburg percussion test" , "Brodie–Trendelenburg percussion test"),
("Budin's sign" , "Budin's sign"),
("Brodie–Trendelenburg test" , "Brodie–Trendelenburg test"),
("Brudziński neck sign" , "Brudziński neck sign"),
("Brudziński cheek sign" , "Brudziński cheek sign"),
("Brudziński symphyseal sign" , "Brudziński symphyseal sign"),
("Brudziński reflex" , "Brudziński reflex"),
("Bruit de Roger" , "Bruit de Roger"),
("Bruns ataxia" , "Bruns ataxia"),
("Bruns nystagmus" , "Bruns nystagmus"),
("Brushfield spots" , "Brushfield spots"),
("Buerger's test" , "Buerger's test"),
("Burton line" , "Burton line"),
("Cabot rings" , "Cabot rings"),
("Caput medusae" , "Caput medusae"),
("Cardarelli's sign" , "Cardarelli's sign"),
("Carey Coombs murmur" , "Carey Coombs murmur"),
("Carnett's sign" , "Carnett's sign"),
("Carvallo's sign" , "Carvallo's sign"),
("Casal collar" , "Casal collar"),
("Casoni test" , "Casoni test"),
("Celsus signs of inflammation" , "Celsus signs of inflammation"),
("Chaddock reflex" , "Chaddock reflex"),
("Chadwick sign" , "Chadwick sign"),
("Charcot's triad" , "Charcot's triad"),
("Charcot's triad" , "Charcot's triad"),
("Charcot–Leyden crystals" , "Charcot–Leyden crystals"),
("Cheyne–Stokes respiration" , "Cheyne–Stokes respiration"),
("Churchill–Cope reflex" , "Churchill–Cope reflex"),
("Chvostek sign" , "Chvostek sign"),
("Claybrook sign" , "Claybrook sign"),
("Clutton's joints" , "Clutton's joints"),
("Codman's triangle" , "Codman's triangle"),
("Comby sign" , "Comby sign"),
("Comolli's sign" , "Comolli's sign"),
("Coombs test" , "Coombs test"),
("Coons fluorescent antibody method" , "Coons fluorescent antibody method"),
("Cornell's sign" , "Cornell's sign"),
("Corrigan pulse" , "Corrigan pulse"),
("Councilman body" , "Councilman body"),
("Courvoisier's law" , "Courvoisier's law"),
("Crichton-Browne sign" , "Crichton-Browne sign"),
("Crowe sign" , "Crowe sign"),
("Cruveilhier–Baumgarten bruit" , "Cruveilhier–Baumgarten bruit"),
("Cullen's sign" , "Cullen's sign"),
("Curschmann spirals" , "Curschmann spirals"),
("Cushing's triad" , "Cushing's triad"),
("Dagher Maneuver" , "Dagher Maneuver"),
("Dahlén–Fuchs nodules" , "Dahlén–Fuchs nodules"),
("Dahl's sign" , "Dahl's sign"),
("Dalrymple sign" , "Dalrymple sign"),
("Dance's sign" , "Dance's sign"),
("Darier's sign" , "Darier's sign"),
("Dawson's fingers" , "Dawson's fingers"),
("De Musset's sign" , "De Musset's sign"),
("Dennie–Morgan fold" , "Dennie–Morgan fold")
ON DUPLICATE KEY UPDATE id=id