INSERT INTO `symptoms` (`id`, `text`) VALUES
("anorexia " , "anorexia "),
("weight loss " , "weight loss "),
("cachexia " , "cachexia "),
("chills and shivering" , "chills and shivering"),
("convulsions " , "convulsions "),
("deformity" , "deformity"),
("discharge" , "discharge"),
("dizziness / Vertigo " , "dizziness / Vertigo "),
("fatigue " , "fatigue "),
("malaise" , "malaise"),
("asthenia" , "asthenia"),
("hypothermia " , "hypothermia "),
("jaundice " , "jaundice "),
("muscle weakness " , "muscle weakness "),
("pyrexia " , "pyrexia "),
("sweats" , "sweats"),
("swelling" , "swelling"),
("Lymphadenopath" , "Lymphadenopath"),
("swollen or painful lymph node" , "swollen or painful lymph node"),
("weight gain " , "weight gain "),
("arrhythmia" , "arrhythmia"),
("bradycardia " , "bradycardia "),
("chest pain " , "chest pain "),
("claudication" , "claudication"),
("palpitations " , "palpitations "),
("tachycardia " , "tachycardia "),
("dry mouth " , "dry mouth "),
("epistaxis " , "epistaxis "),
("halitosis" , "halitosis"),
("hearing loss" , "hearing loss"),
("nasal discharge" , "nasal discharge"),
("otalgia " , "otalgia "),
("otorrhea " , "otorrhea "),
("sore throat" , "sore throat"),
("toothache" , "toothache"),
("tinnitus " , "tinnitus "),
("trismus" , "trismus"),
("abdominal pain " , "abdominal pain "),
("bloating " , "bloating "),
("belching " , "belching "),
("Hematemesis" , "Hematemesis"),
("blood in stool: melena " , "blood in stool: melena "),
("constipation " , "constipation "),
("diarrhea " , "diarrhea "),
("dysphagia " , "dysphagia "),
("dyspepsia " , "dyspepsia "),
("fecal incontinence" , "fecal incontinence"),
("flatulence " , "flatulence "),
("heartburn" , "heartburn"),
("nausea " , "nausea "),
("odynophagia" , "odynophagia"),
("proctalgia fugax" , "proctalgia fugax"),
("pyrosis " , "pyrosis "),
("Rectal tenesmus" , "Rectal tenesmus"),
("steatorrhea" , "steatorrhea"),
("vomiting " , "vomiting "),
("alopecia" , "alopecia"),
("hirsutism" , "hirsutism"),
("hypertrichosis" , "hypertrichosis"),
("abrasion" , "abrasion"),
("anasarca " , "anasarca "),
("bleeding into the skin" , "bleeding into the skin"),
("petechia" , "petechia"),
("purpura" , "purpura"),
("ecchymosis and bruising " , "ecchymosis and bruising "),
("blister " , "blister "),
("edema " , "edema "),
("itching " , "itching "),
("Janeway lesions and Osler's node" , "Janeway lesions and Osler's node"),
("laceration" , "laceration"),
("rash " , "rash "),
("urticaria " , "urticaria "),
("abnormal posturing" , "abnormal posturing"),
("acalculia" , "acalculia"),
("agnosia" , "agnosia"),
("alexia" , "alexia"),
("amnesia" , "amnesia"),
("anomia" , "anomia"),
("anosognosia" , "anosognosia"),
("aphasia and apraxia" , "aphasia and apraxia"),
("apraxia" , "apraxia"),
("ataxia" , "ataxia"),
("cataplexy " , "cataplexy "),
("confusion" , "confusion"),
("dysarthria" , "dysarthria"),
("dysdiadochokinesia" , "dysdiadochokinesia"),
("dysgraphia" , "dysgraphia"),
("hallucination" , "hallucination"),
("headache " , "headache "),
("hypokinetic movement disorder:" , "hypokinetic movement disorder:"),
("akinesia" , "akinesia"),
("bradykinesia" , "bradykinesia"),
("hyperkinetic movement disorder:" , "hyperkinetic movement disorder:"),
("akathisia" , "akathisia"),
("athetosis" , "athetosis"),
("ballismus" , "ballismus"),
("blepharospasm" , "blepharospasm"),
("chorea" , "chorea"),
("dystonia" , "dystonia"),
("fasciculation" , "fasciculation"),
("muscle cramps " , "muscle cramps "),
("myoclonus" , "myoclonus"),
("opsoclonus" , "opsoclonus"),
("tic" , "tic"),
("tremor" , "tremor"),
("flapping tremor" , "flapping tremor"),
("insomnia " , "insomnia "),
("Lhermitte's sign " , "Lhermitte's sign "),
("loss of consciousness" , "loss of consciousness"),
("Syncope " , "Syncope "),
("neck stiffness" , "neck stiffness"),
("opisthotonus" , "opisthotonus"),
("paralysis and paresis" , "paralysis and paresis"),
("paresthesia " , "paresthesia "),
("prosopagnosia" , "prosopagnosia"),
("somnolence " , "somnolence "),
("abnormal vaginal bleeding" , "abnormal vaginal bleeding"),
("vaginal bleeding in early pregnancy / miscarriage" , "vaginal bleeding in early pregnancy / miscarriage"),
("vaginal bleeding in late pregnancy" , "vaginal bleeding in late pregnancy"),
("amenorrhea" , "amenorrhea"),
("infertility" , "infertility"),
("painful intercourse " , "painful intercourse "),
("pelvic pain" , "pelvic pain"),
("vaginal discharge" , "vaginal discharge"),
("amaurosis fugax " , "amaurosis fugax "),
("blurred vision" , "blurred vision"),
("Dalrymple's sign" , "Dalrymple's sign"),
("double vision " , "double vision "),
("exophthalmos " , "exophthalmos "),
("mydriasis/miosis " , "mydriasis/miosis "),
("nystagmus" , "nystagmus"),
("amusia" , "amusia"),
("anhedonia" , "anhedonia"),
("anxiety" , "anxiety"),
("apathy" , "apathy"),
("confabulation" , "confabulation"),
("depression" , "depression"),
("delusion" , "delusion"),
("euphoria" , "euphoria"),
("homicidal ideation" , "homicidal ideation"),
("irritability" , "irritability"),
("mania " , "mania "),
("paranoid ideation" , "paranoid ideation"),
("suicidal ideation" , "suicidal ideation"),
("apnea and hypopnea" , "apnea and hypopnea"),
("cough " , "cough "),
("dyspnea " , "dyspnea "),
("bradypnea " , "bradypnea "),
("orthopnea and platypnea" , "orthopnea and platypnea"),
("trepopnea" , "trepopnea"),
("hemoptysis " , "hemoptysis "),
("pleuritic chest pain" , "pleuritic chest pain"),
("sputum production " , "sputum production "),
("arthralgia" , "arthralgia"),
("back pain" , "back pain"),
("sciatica" , "sciatica"),
("dysuria " , "dysuria "),
("hematospermia" , "hematospermia"),
("hematuria " , "hematuria "),
("impotence " , "impotence "),
("polyuria " , "polyuria "),
("retrograde ejaculation" , "retrograde ejaculation"),
("strangury" , "strangury"),
("urethral discharge" , "urethral discharge"),
("urinary frequency " , "urinary frequency "),
("urinary incontinence " , "urinary incontinence "),
("urinary retention" , "urinary retention")
ON DUPLICATE KEY UPDATE id=id
